INSERT INTO [TestSchema].[Course] VALUES('Accounting',547);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',863);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',771);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',106);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',945);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',7);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',612);
INSERT INTO [TestSchema].[Course] VALUES('Health',845);
INSERT INTO [TestSchema].[Course] VALUES('Music',272);
INSERT INTO [TestSchema].[Course] VALUES('Latin',451);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',171);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',513);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',954);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',574);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',413);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',695);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',798);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',65);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',284);
INSERT INTO [TestSchema].[Course] VALUES('Geography',133);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',359);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',989);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',753);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',323);
INSERT INTO [TestSchema].[Course] VALUES('German',814);
INSERT INTO [TestSchema].[Course] VALUES('Health',771);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',466);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',544);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',888);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',103);
INSERT INTO [TestSchema].[Course] VALUES('Music',247);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',965);
INSERT INTO [TestSchema].[Course] VALUES('Science',107);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',921);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',626);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',991);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',835);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',670);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',784);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',347);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',167);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',902);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',934);
INSERT INTO [TestSchema].[Course] VALUES('Health',958);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',322);
INSERT INTO [TestSchema].[Course] VALUES('Music',159);
INSERT INTO [TestSchema].[Course] VALUES('French',975);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',358);
INSERT INTO [TestSchema].[Course] VALUES('Latin',582);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',285);
INSERT INTO [TestSchema].[Course] VALUES('German',100);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',547);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',677);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',189);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',351);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',988);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',417);
INSERT INTO [TestSchema].[Course] VALUES('German',116);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',487);
INSERT INTO [TestSchema].[Course] VALUES('Science',305);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',623);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',424);
INSERT INTO [TestSchema].[Course] VALUES('English IV',639);
INSERT INTO [TestSchema].[Course] VALUES('Economics',218);
INSERT INTO [TestSchema].[Course] VALUES('Art',489);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',43);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',837);
INSERT INTO [TestSchema].[Course] VALUES('German',834);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',854);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',68);
INSERT INTO [TestSchema].[Course] VALUES('English IV',482);
INSERT INTO [TestSchema].[Course] VALUES('English IV',426);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',304);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',104);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',735);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',483);
INSERT INTO [TestSchema].[Course] VALUES('English IV',446);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',549);
INSERT INTO [TestSchema].[Course] VALUES('Latin',153);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',377);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',360);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',131);
INSERT INTO [TestSchema].[Course] VALUES('Speech',877);
INSERT INTO [TestSchema].[Course] VALUES('Latin',929);
INSERT INTO [TestSchema].[Course] VALUES('Science',334);
INSERT INTO [TestSchema].[Course] VALUES('French',992);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',153);
INSERT INTO [TestSchema].[Course] VALUES('Latin',953);
INSERT INTO [TestSchema].[Course] VALUES('Music',719);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',32);
INSERT INTO [TestSchema].[Course] VALUES('History',368);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',250);
INSERT INTO [TestSchema].[Course] VALUES('Art',219);
INSERT INTO [TestSchema].[Course] VALUES('Health',588);
INSERT INTO [TestSchema].[Course] VALUES('Art',626);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',436);
INSERT INTO [TestSchema].[Course] VALUES('Speech',509);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',997);
INSERT INTO [TestSchema].[Course] VALUES('Music',209);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',524);
INSERT INTO [TestSchema].[Course] VALUES('English IV',462);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',473);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',519);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',209);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',894);
INSERT INTO [TestSchema].[Course] VALUES('History',235);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',181);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',838);
INSERT INTO [TestSchema].[Course] VALUES('Latin',954);
INSERT INTO [TestSchema].[Course] VALUES('German',432);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',366);
INSERT INTO [TestSchema].[Course] VALUES('Latin',616);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',90);
INSERT INTO [TestSchema].[Course] VALUES('English IV',92);
INSERT INTO [TestSchema].[Course] VALUES('Music',950);
INSERT INTO [TestSchema].[Course] VALUES('Health',75);
INSERT INTO [TestSchema].[Course] VALUES('Latin',497);
INSERT INTO [TestSchema].[Course] VALUES('Health',785);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',937);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',459);
INSERT INTO [TestSchema].[Course] VALUES('English IV',472);
INSERT INTO [TestSchema].[Course] VALUES('Geography',94);
INSERT INTO [TestSchema].[Course] VALUES('English IV',646);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',461);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',24);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',324);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',344);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',983);
INSERT INTO [TestSchema].[Course] VALUES('French',246);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',119);
INSERT INTO [TestSchema].[Course] VALUES('German',790);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',548);
INSERT INTO [TestSchema].[Course] VALUES('Science',190);
INSERT INTO [TestSchema].[Course] VALUES('Music',634);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',344);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',12);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',693);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',724);
INSERT INTO [TestSchema].[Course] VALUES('Music',847);
INSERT INTO [TestSchema].[Course] VALUES('History',808);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',889);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',267);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',352);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',600);
INSERT INTO [TestSchema].[Course] VALUES('German',699);
INSERT INTO [TestSchema].[Course] VALUES('History',261);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',922);
INSERT INTO [TestSchema].[Course] VALUES('Music',547);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',541);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',171);
INSERT INTO [TestSchema].[Course] VALUES('English IV',671);
INSERT INTO [TestSchema].[Course] VALUES('Latin',37);
INSERT INTO [TestSchema].[Course] VALUES('Health',37);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',363);
INSERT INTO [TestSchema].[Course] VALUES('History',603);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',674);
INSERT INTO [TestSchema].[Course] VALUES('Art',212);
INSERT INTO [TestSchema].[Course] VALUES('English IV',279);
INSERT INTO [TestSchema].[Course] VALUES('Geography',651);
INSERT INTO [TestSchema].[Course] VALUES('Speech',867);
INSERT INTO [TestSchema].[Course] VALUES('German',691);
INSERT INTO [TestSchema].[Course] VALUES('Economics',800);
INSERT INTO [TestSchema].[Course] VALUES('Geography',73);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',990);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',549);
INSERT INTO [TestSchema].[Course] VALUES('German',736);
INSERT INTO [TestSchema].[Course] VALUES('Art',86);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',115);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',675);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',865);
INSERT INTO [TestSchema].[Course] VALUES('Latin',656);
INSERT INTO [TestSchema].[Course] VALUES('English IV',567);
INSERT INTO [TestSchema].[Course] VALUES('Art',590);
INSERT INTO [TestSchema].[Course] VALUES('History',707);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',12);
INSERT INTO [TestSchema].[Course] VALUES('Economics',903);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',7);
INSERT INTO [TestSchema].[Course] VALUES('Art',664);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',162);
INSERT INTO [TestSchema].[Course] VALUES('Latin',618);
INSERT INTO [TestSchema].[Course] VALUES('Latin',420);
INSERT INTO [TestSchema].[Course] VALUES('Latin',699);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',970);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',904);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',220);
INSERT INTO [TestSchema].[Course] VALUES('English IV',404);
INSERT INTO [TestSchema].[Course] VALUES('Geography',781);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',516);
INSERT INTO [TestSchema].[Course] VALUES('English IV',896);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',489);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',385);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',391);
INSERT INTO [TestSchema].[Course] VALUES('Geography',266);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',965);
INSERT INTO [TestSchema].[Course] VALUES('Geography',789);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',766);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',957);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',520);
INSERT INTO [TestSchema].[Course] VALUES('Health',652);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',23);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',367);
INSERT INTO [TestSchema].[Course] VALUES('Latin',370);
INSERT INTO [TestSchema].[Course] VALUES('Speech',65);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',114);
INSERT INTO [TestSchema].[Course] VALUES('Geography',483);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',310);
INSERT INTO [TestSchema].[Course] VALUES('English IV',468);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',559);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',569);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',167);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',735);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',969);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',586);
INSERT INTO [TestSchema].[Course] VALUES('Health',117);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',407);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',687);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',785);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',434);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',32);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',16);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',728);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',603);
INSERT INTO [TestSchema].[Course] VALUES('Economics',597);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',249);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',362);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',127);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',967);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',155);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',980);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',75);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',713);
INSERT INTO [TestSchema].[Course] VALUES('History',673);
INSERT INTO [TestSchema].[Course] VALUES('Speech',637);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',569);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',384);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',986);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',603);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',402);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',215);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',714);
INSERT INTO [TestSchema].[Course] VALUES('German',437);
INSERT INTO [TestSchema].[Course] VALUES('Art',499);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',693);
INSERT INTO [TestSchema].[Course] VALUES('Speech',795);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',445);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',456);
INSERT INTO [TestSchema].[Course] VALUES('Art',657);
INSERT INTO [TestSchema].[Course] VALUES('Speech',723);
INSERT INTO [TestSchema].[Course] VALUES('Economics',213);
INSERT INTO [TestSchema].[Course] VALUES('Latin',827);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',843);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',757);
INSERT INTO [TestSchema].[Course] VALUES('Science',515);
INSERT INTO [TestSchema].[Course] VALUES('Music',430);
INSERT INTO [TestSchema].[Course] VALUES('Science',491);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',335);
INSERT INTO [TestSchema].[Course] VALUES('Economics',343);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',941);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',754);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',969);
INSERT INTO [TestSchema].[Course] VALUES('Art',752);
INSERT INTO [TestSchema].[Course] VALUES('Health',425);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',668);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',181);
INSERT INTO [TestSchema].[Course] VALUES('Latin',8);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',635);
INSERT INTO [TestSchema].[Course] VALUES('Music',676);
INSERT INTO [TestSchema].[Course] VALUES('Speech',331);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',219);
INSERT INTO [TestSchema].[Course] VALUES('History',391);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',225);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',401);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',550);
INSERT INTO [TestSchema].[Course] VALUES('Art',631);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',695);
INSERT INTO [TestSchema].[Course] VALUES('Art',721);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',969);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',298);
INSERT INTO [TestSchema].[Course] VALUES('German',955);
INSERT INTO [TestSchema].[Course] VALUES('History',570);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',109);
INSERT INTO [TestSchema].[Course] VALUES('Economics',230);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',670);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',799);
INSERT INTO [TestSchema].[Course] VALUES('Health',569);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',518);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',377);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',757);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',275);
INSERT INTO [TestSchema].[Course] VALUES('Music',948);
INSERT INTO [TestSchema].[Course] VALUES('Health',381);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',271);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',205);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',305);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',368);
INSERT INTO [TestSchema].[Course] VALUES('German',102);
INSERT INTO [TestSchema].[Course] VALUES('Latin',690);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',296);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',329);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',468);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',181);
INSERT INTO [TestSchema].[Course] VALUES('Latin',187);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',468);
INSERT INTO [TestSchema].[Course] VALUES('Science',70);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',88);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',891);
INSERT INTO [TestSchema].[Course] VALUES('Health',310);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',121);
INSERT INTO [TestSchema].[Course] VALUES('Health',194);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',360);
INSERT INTO [TestSchema].[Course] VALUES('Economics',754);
INSERT INTO [TestSchema].[Course] VALUES('Latin',311);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',783);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',802);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',270);
INSERT INTO [TestSchema].[Course] VALUES('Art',865);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',818);
INSERT INTO [TestSchema].[Course] VALUES('Economics',508);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',237);
INSERT INTO [TestSchema].[Course] VALUES('Economics',554);
INSERT INTO [TestSchema].[Course] VALUES('Art',121);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',743);
INSERT INTO [TestSchema].[Course] VALUES('History',273);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',650);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',767);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',567);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',476);
INSERT INTO [TestSchema].[Course] VALUES('Art',736);
INSERT INTO [TestSchema].[Course] VALUES('Science',642);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',27);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',426);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',134);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',238);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',850);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',375);
INSERT INTO [TestSchema].[Course] VALUES('Health',447);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',655);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',360);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',225);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',133);
INSERT INTO [TestSchema].[Course] VALUES('English IV',907);
INSERT INTO [TestSchema].[Course] VALUES('Art',721);
INSERT INTO [TestSchema].[Course] VALUES('Speech',429);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',963);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',721);
INSERT INTO [TestSchema].[Course] VALUES('Music',785);
INSERT INTO [TestSchema].[Course] VALUES('Economics',433);
INSERT INTO [TestSchema].[Course] VALUES('Speech',551);
INSERT INTO [TestSchema].[Course] VALUES('French',767);
INSERT INTO [TestSchema].[Course] VALUES('Speech',26);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',582);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',434);
INSERT INTO [TestSchema].[Course] VALUES('Geography',164);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',465);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',627);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',988);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',650);
INSERT INTO [TestSchema].[Course] VALUES('Health',3);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',859);
INSERT INTO [TestSchema].[Course] VALUES('Economics',662);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',489);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',131);
INSERT INTO [TestSchema].[Course] VALUES('Geography',907);
INSERT INTO [TestSchema].[Course] VALUES('Art',301);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',831);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',87);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',21);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',768);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',560);
INSERT INTO [TestSchema].[Course] VALUES('Speech',495);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',281);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',204);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',307);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',805);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',642);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',680);
INSERT INTO [TestSchema].[Course] VALUES('Music',990);
INSERT INTO [TestSchema].[Course] VALUES('French',332);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',667);
INSERT INTO [TestSchema].[Course] VALUES('English IV',168);
INSERT INTO [TestSchema].[Course] VALUES('German',534);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',261);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',796);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',575);
INSERT INTO [TestSchema].[Course] VALUES('English IV',907);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',872);
INSERT INTO [TestSchema].[Course] VALUES('Science',979);
INSERT INTO [TestSchema].[Course] VALUES('Geography',212);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',816);
INSERT INTO [TestSchema].[Course] VALUES('Music',773);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',187);
INSERT INTO [TestSchema].[Course] VALUES('French',369);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',140);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',582);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',980);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',442);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',479);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',62);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',609);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',43);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',615);
INSERT INTO [TestSchema].[Course] VALUES('Economics',849);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',248);
INSERT INTO [TestSchema].[Course] VALUES('Economics',313);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',321);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',745);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',581);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',985);
INSERT INTO [TestSchema].[Course] VALUES('Art',86);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',668);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',833);
INSERT INTO [TestSchema].[Course] VALUES('Geography',358);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',451);
INSERT INTO [TestSchema].[Course] VALUES('Health',733);
INSERT INTO [TestSchema].[Course] VALUES('Speech',5);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',9);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',251);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',103);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',694);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',465);
INSERT INTO [TestSchema].[Course] VALUES('Health',482);
INSERT INTO [TestSchema].[Course] VALUES('Speech',167);
INSERT INTO [TestSchema].[Course] VALUES('History',461);
INSERT INTO [TestSchema].[Course] VALUES('Geography',623);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',338);
INSERT INTO [TestSchema].[Course] VALUES('Geography',741);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',728);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',58);
INSERT INTO [TestSchema].[Course] VALUES('French',110);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',299);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',734);
INSERT INTO [TestSchema].[Course] VALUES('Speech',918);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',704);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',125);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',348);
INSERT INTO [TestSchema].[Course] VALUES('History',296);
INSERT INTO [TestSchema].[Course] VALUES('Economics',85);
INSERT INTO [TestSchema].[Course] VALUES('Art',521);
INSERT INTO [TestSchema].[Course] VALUES('German',920);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',240);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',44);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',319);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',644);
INSERT INTO [TestSchema].[Course] VALUES('Latin',692);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',825);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',610);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',321);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',938);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',740);
INSERT INTO [TestSchema].[Course] VALUES('Science',562);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',943);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',681);
INSERT INTO [TestSchema].[Course] VALUES('Geography',776);
INSERT INTO [TestSchema].[Course] VALUES('Music',976);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',519);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',607);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',908);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',537);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',337);
INSERT INTO [TestSchema].[Course] VALUES('Art',292);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',632);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',874);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',657);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',145);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',57);
INSERT INTO [TestSchema].[Course] VALUES('Health',435);
INSERT INTO [TestSchema].[Course] VALUES('Health',529);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',440);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',23);
INSERT INTO [TestSchema].[Course] VALUES('History',157);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',972);
INSERT INTO [TestSchema].[Course] VALUES('Latin',691);
INSERT INTO [TestSchema].[Course] VALUES('Latin',967);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',637);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',348);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',489);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',939);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',504);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',51);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',414);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',132);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',676);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',447);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',489);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',476);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',7);
INSERT INTO [TestSchema].[Course] VALUES('Geography',829);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',784);
INSERT INTO [TestSchema].[Course] VALUES('Health',223);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',806);
INSERT INTO [TestSchema].[Course] VALUES('Geography',112);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',852);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',206);
INSERT INTO [TestSchema].[Course] VALUES('Health',749);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',600);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',70);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',834);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',237);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',284);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',495);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',103);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',930);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',902);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',925);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',23);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',807);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',103);
INSERT INTO [TestSchema].[Course] VALUES('English IV',914);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',924);
INSERT INTO [TestSchema].[Course] VALUES('French',618);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',168);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',206);
INSERT INTO [TestSchema].[Course] VALUES('Geography',348);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',254);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',686);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',390);
INSERT INTO [TestSchema].[Course] VALUES('English IV',436);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',962);
INSERT INTO [TestSchema].[Course] VALUES('Music',807);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',246);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',756);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',701);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',602);
INSERT INTO [TestSchema].[Course] VALUES('Latin',13);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',216);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',272);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',249);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',881);
INSERT INTO [TestSchema].[Course] VALUES('English IV',627);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',583);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',147);
INSERT INTO [TestSchema].[Course] VALUES('Science',331);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',442);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',683);
INSERT INTO [TestSchema].[Course] VALUES('English IV',387);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',586);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',283);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',11);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',65);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',463);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',878);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',483);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',317);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',107);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',874);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',652);
INSERT INTO [TestSchema].[Course] VALUES('Latin',338);
INSERT INTO [TestSchema].[Course] VALUES('Science',658);
INSERT INTO [TestSchema].[Course] VALUES('French',402);
INSERT INTO [TestSchema].[Course] VALUES('History',327);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',268);
INSERT INTO [TestSchema].[Course] VALUES('Health',100);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',258);
INSERT INTO [TestSchema].[Course] VALUES('History',473);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',719);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',272);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',402);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',133);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',742);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',117);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',346);
INSERT INTO [TestSchema].[Course] VALUES('Art',472);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',983);
INSERT INTO [TestSchema].[Course] VALUES('Speech',665);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',156);
INSERT INTO [TestSchema].[Course] VALUES('Economics',34);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',110);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',130);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',669);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',586);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',162);
INSERT INTO [TestSchema].[Course] VALUES('Health',987);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',354);
INSERT INTO [TestSchema].[Course] VALUES('Economics',541);
INSERT INTO [TestSchema].[Course] VALUES('German',103);
INSERT INTO [TestSchema].[Course] VALUES('Music',787);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',150);
INSERT INTO [TestSchema].[Course] VALUES('French',804);
INSERT INTO [TestSchema].[Course] VALUES('Music',196);
INSERT INTO [TestSchema].[Course] VALUES('English IV',596);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',603);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',280);
INSERT INTO [TestSchema].[Course] VALUES('Science',413);
INSERT INTO [TestSchema].[Course] VALUES('Economics',81);
INSERT INTO [TestSchema].[Course] VALUES('Geography',57);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',709);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',902);
INSERT INTO [TestSchema].[Course] VALUES('Geography',646);
INSERT INTO [TestSchema].[Course] VALUES('Health',988);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',407);
INSERT INTO [TestSchema].[Course] VALUES('French',103);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',945);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',693);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',648);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',509);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',17);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',307);
INSERT INTO [TestSchema].[Course] VALUES('Art',445);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',392);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',16);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',381);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',97);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',570);
INSERT INTO [TestSchema].[Course] VALUES('Latin',13);
INSERT INTO [TestSchema].[Course] VALUES('Geography',874);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',303);
INSERT INTO [TestSchema].[Course] VALUES('German',930);
INSERT INTO [TestSchema].[Course] VALUES('Geography',511);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',480);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',546);
INSERT INTO [TestSchema].[Course] VALUES('Music',826);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',580);
INSERT INTO [TestSchema].[Course] VALUES('Science',904);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',532);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',624);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',282);
INSERT INTO [TestSchema].[Course] VALUES('Science',29);
INSERT INTO [TestSchema].[Course] VALUES('French',142);
INSERT INTO [TestSchema].[Course] VALUES('Speech',416);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',306);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',106);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',716);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',535);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',400);
INSERT INTO [TestSchema].[Course] VALUES('Science',461);
INSERT INTO [TestSchema].[Course] VALUES('English IV',257);
INSERT INTO [TestSchema].[Course] VALUES('Art',203);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',53);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',872);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',278);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',416);
INSERT INTO [TestSchema].[Course] VALUES('Geography',458);
INSERT INTO [TestSchema].[Course] VALUES('Latin',848);
INSERT INTO [TestSchema].[Course] VALUES('Geography',124);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',933);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',675);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',99);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',189);
INSERT INTO [TestSchema].[Course] VALUES('History',775);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',682);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',978);
INSERT INTO [TestSchema].[Course] VALUES('Music',470);
INSERT INTO [TestSchema].[Course] VALUES('History',653);
INSERT INTO [TestSchema].[Course] VALUES('Music',37);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',475);
INSERT INTO [TestSchema].[Course] VALUES('History',778);
INSERT INTO [TestSchema].[Course] VALUES('French',485);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',329);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',109);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',530);
INSERT INTO [TestSchema].[Course] VALUES('Economics',741);
INSERT INTO [TestSchema].[Course] VALUES('Art',299);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',678);
INSERT INTO [TestSchema].[Course] VALUES('French',889);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',533);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',114);
INSERT INTO [TestSchema].[Course] VALUES('Health',196);
INSERT INTO [TestSchema].[Course] VALUES('Science',213);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',613);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',312);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',27);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',927);
INSERT INTO [TestSchema].[Course] VALUES('Health',83);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',232);
INSERT INTO [TestSchema].[Course] VALUES('Art',472);
INSERT INTO [TestSchema].[Course] VALUES('German',152);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',671);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',299);
INSERT INTO [TestSchema].[Course] VALUES('Art',1);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',591);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',405);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',774);
INSERT INTO [TestSchema].[Course] VALUES('Health',138);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',343);
INSERT INTO [TestSchema].[Course] VALUES('History',901);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',411);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',440);
INSERT INTO [TestSchema].[Course] VALUES('Art',446);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',70);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',517);
INSERT INTO [TestSchema].[Course] VALUES('French',309);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',929);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',641);
INSERT INTO [TestSchema].[Course] VALUES('Geography',999);
INSERT INTO [TestSchema].[Course] VALUES('Art',939);
INSERT INTO [TestSchema].[Course] VALUES('Science',116);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',596);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',149);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',42);
INSERT INTO [TestSchema].[Course] VALUES('History',543);
INSERT INTO [TestSchema].[Course] VALUES('Art',794);
INSERT INTO [TestSchema].[Course] VALUES('Art',83);
INSERT INTO [TestSchema].[Course] VALUES('History',753);
INSERT INTO [TestSchema].[Course] VALUES('Science',584);
INSERT INTO [TestSchema].[Course] VALUES('Health',764);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',911);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',354);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',804);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',704);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',42);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',107);
INSERT INTO [TestSchema].[Course] VALUES('English IV',307);
INSERT INTO [TestSchema].[Course] VALUES('Health',96);
INSERT INTO [TestSchema].[Course] VALUES('Health',325);
INSERT INTO [TestSchema].[Course] VALUES('Science',827);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',883);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',75);
INSERT INTO [TestSchema].[Course] VALUES('French',747);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',823);
INSERT INTO [TestSchema].[Course] VALUES('Health',614);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',506);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',221);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',321);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',389);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',395);
INSERT INTO [TestSchema].[Course] VALUES('Speech',688);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',204);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',869);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',677);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',165);
INSERT INTO [TestSchema].[Course] VALUES('Geography',905);
INSERT INTO [TestSchema].[Course] VALUES('English IV',867);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',491);
INSERT INTO [TestSchema].[Course] VALUES('Geography',309);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',302);
INSERT INTO [TestSchema].[Course] VALUES('Economics',676);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',792);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',542);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',137);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',348);
INSERT INTO [TestSchema].[Course] VALUES('English IV',279);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',845);
INSERT INTO [TestSchema].[Course] VALUES('German',365);
INSERT INTO [TestSchema].[Course] VALUES('History',621);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',670);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',647);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',505);
INSERT INTO [TestSchema].[Course] VALUES('French',505);
INSERT INTO [TestSchema].[Course] VALUES('German',438);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',75);
INSERT INTO [TestSchema].[Course] VALUES('Science',425);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',245);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',973);
INSERT INTO [TestSchema].[Course] VALUES('Speech',842);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',953);
INSERT INTO [TestSchema].[Course] VALUES('Geography',301);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',66);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',806);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',499);
INSERT INTO [TestSchema].[Course] VALUES('Health',346);
INSERT INTO [TestSchema].[Course] VALUES('History',465);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',143);
INSERT INTO [TestSchema].[Course] VALUES('Art',832);
INSERT INTO [TestSchema].[Course] VALUES('History',530);
INSERT INTO [TestSchema].[Course] VALUES('History',126);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',364);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',668);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',938);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',534);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',206);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',406);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',625);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',11);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',345);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',723);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',663);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',163);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',770);
INSERT INTO [TestSchema].[Course] VALUES('Health',433);
INSERT INTO [TestSchema].[Course] VALUES('History',83);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',123);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',447);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',703);
INSERT INTO [TestSchema].[Course] VALUES('Health',268);
INSERT INTO [TestSchema].[Course] VALUES('Latin',863);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',592);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',484);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',837);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',105);
INSERT INTO [TestSchema].[Course] VALUES('French',981);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',921);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',540);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',717);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',464);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',344);
INSERT INTO [TestSchema].[Course] VALUES('History',270);
INSERT INTO [TestSchema].[Course] VALUES('Music',846);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',590);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',602);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',899);
INSERT INTO [TestSchema].[Course] VALUES('English IV',444);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',840);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',786);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',265);
INSERT INTO [TestSchema].[Course] VALUES('French',993);
INSERT INTO [TestSchema].[Course] VALUES('English IV',590);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',272);
INSERT INTO [TestSchema].[Course] VALUES('Latin',785);
INSERT INTO [TestSchema].[Course] VALUES('Music',40);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',855);
INSERT INTO [TestSchema].[Course] VALUES('Geography',210);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',608);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',833);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',722);
INSERT INTO [TestSchema].[Course] VALUES('Art',44);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',814);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',641);
INSERT INTO [TestSchema].[Course] VALUES('Speech',677);
INSERT INTO [TestSchema].[Course] VALUES('French',986);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',961);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',351);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',843);
INSERT INTO [TestSchema].[Course] VALUES('Art',653);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',10);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',714);
INSERT INTO [TestSchema].[Course] VALUES('Music',787);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',197);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',128);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',784);
INSERT INTO [TestSchema].[Course] VALUES('Science',786);
INSERT INTO [TestSchema].[Course] VALUES('Economics',372);
INSERT INTO [TestSchema].[Course] VALUES('Music',486);
INSERT INTO [TestSchema].[Course] VALUES('Art',539);
INSERT INTO [TestSchema].[Course] VALUES('French',252);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',285);
INSERT INTO [TestSchema].[Course] VALUES('History',309);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',738);
INSERT INTO [TestSchema].[Course] VALUES('Science',737);
INSERT INTO [TestSchema].[Course] VALUES('Music',588);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',967);
INSERT INTO [TestSchema].[Course] VALUES('Economics',302);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',271);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',224);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',854);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',517);
INSERT INTO [TestSchema].[Course] VALUES('Speech',744);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',134);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',250);
INSERT INTO [TestSchema].[Course] VALUES('Geography',449);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',451);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',125);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',600);
INSERT INTO [TestSchema].[Course] VALUES('Economics',986);
INSERT INTO [TestSchema].[Course] VALUES('Health',164);
INSERT INTO [TestSchema].[Course] VALUES('Latin',75);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',426);
INSERT INTO [TestSchema].[Course] VALUES('German',253);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',173);
INSERT INTO [TestSchema].[Course] VALUES('French',9);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',758);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',684);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',112);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',511);
INSERT INTO [TestSchema].[Course] VALUES('French',985);
INSERT INTO [TestSchema].[Course] VALUES('History',982);
INSERT INTO [TestSchema].[Course] VALUES('Speech',826);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',168);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',332);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',237);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',761);
INSERT INTO [TestSchema].[Course] VALUES('Earth Science',747);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',755);
INSERT INTO [TestSchema].[Course] VALUES('Speech',239);
INSERT INTO [TestSchema].[Course] VALUES('Dramatics',514);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',313);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',63);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',102);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',429);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',270);
INSERT INTO [TestSchema].[Course] VALUES('Art',946);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',683);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',981);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',28);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',997);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',998);
INSERT INTO [TestSchema].[Course] VALUES('History',298);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',976);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',879);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',667);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',383);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',28);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',939);
INSERT INTO [TestSchema].[Course] VALUES('History',602);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',625);
INSERT INTO [TestSchema].[Course] VALUES('English IV',424);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',650);
INSERT INTO [TestSchema].[Course] VALUES('History',866);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',873);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',909);
INSERT INTO [TestSchema].[Course] VALUES('English IV',636);
INSERT INTO [TestSchema].[Course] VALUES('French',581);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',805);
INSERT INTO [TestSchema].[Course] VALUES('Geography',417);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',734);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',943);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',36);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',596);
INSERT INTO [TestSchema].[Course] VALUES('Handwriting',417);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',972);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',806);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',73);
INSERT INTO [TestSchema].[Course] VALUES('Speech',975);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',602);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',329);
INSERT INTO [TestSchema].[Course] VALUES('Speech',330);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',885);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',811);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',351);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',377);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',850);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',381);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',402);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',595);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',662);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',899);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',863);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',540);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',467);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',139);
INSERT INTO [TestSchema].[Course] VALUES('Physical Education',459);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',538);
INSERT INTO [TestSchema].[Course] VALUES('Geography',569);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',749);
INSERT INTO [TestSchema].[Course] VALUES('Accounting',12);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',663);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',125);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',863);
INSERT INTO [TestSchema].[Course] VALUES('Geography',532);
INSERT INTO [TestSchema].[Course] VALUES('English IV',251);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',773);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',378);
INSERT INTO [TestSchema].[Course] VALUES('Economics',760);
INSERT INTO [TestSchema].[Course] VALUES('Latin',181);
INSERT INTO [TestSchema].[Course] VALUES('Health',779);
INSERT INTO [TestSchema].[Course] VALUES('Geography',376);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',774);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',420);
INSERT INTO [TestSchema].[Course] VALUES('Economics',197);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',157);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',40);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',816);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',189);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',248);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',332);
INSERT INTO [TestSchema].[Course] VALUES('Economics',193);
INSERT INTO [TestSchema].[Course] VALUES('Leadership',678);
INSERT INTO [TestSchema].[Course] VALUES('Latin',664);
INSERT INTO [TestSchema].[Course] VALUES('Health',999);
INSERT INTO [TestSchema].[Course] VALUES('Geography',315);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',718);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',935);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',378);
INSERT INTO [TestSchema].[Course] VALUES('Science',729);
INSERT INTO [TestSchema].[Course] VALUES('Sociology',674);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',874);
INSERT INTO [TestSchema].[Course] VALUES('Science',191);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',147);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',958);
INSERT INTO [TestSchema].[Course] VALUES('Economics',289);
INSERT INTO [TestSchema].[Course] VALUES('Mathematics',710);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',358);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',894);
INSERT INTO [TestSchema].[Course] VALUES('History',744);
INSERT INTO [TestSchema].[Course] VALUES('Resource Program',275);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',474);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',990);
INSERT INTO [TestSchema].[Course] VALUES('French',785);
INSERT INTO [TestSchema].[Course] VALUES('Art',943);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',531);
INSERT INTO [TestSchema].[Course] VALUES('Latin',666);
INSERT INTO [TestSchema].[Course] VALUES('Geography',95);
INSERT INTO [TestSchema].[Course] VALUES('Latin',595);
INSERT INTO [TestSchema].[Course] VALUES('Latin',929);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',805);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',726);
INSERT INTO [TestSchema].[Course] VALUES('French',772);
INSERT INTO [TestSchema].[Course] VALUES('Latin',901);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',702);
INSERT INTO [TestSchema].[Course] VALUES('Trigonometry',31);
INSERT INTO [TestSchema].[Course] VALUES('American Literature',497);
INSERT INTO [TestSchema].[Course] VALUES('Spanish',910);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',916);
INSERT INTO [TestSchema].[Course] VALUES('Language Arts',236);
INSERT INTO [TestSchema].[Course] VALUES('Speech',961);
INSERT INTO [TestSchema].[Course] VALUES('German',950);
INSERT INTO [TestSchema].[Course] VALUES('Geography',938);
INSERT INTO [TestSchema].[Course] VALUES('English IV',698);
INSERT INTO [TestSchema].[Course] VALUES('Speech',318);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',715);
INSERT INTO [TestSchema].[Course] VALUES('Design and technology',326);
INSERT INTO [TestSchema].[Course] VALUES('Instrumental Music',17);
INSERT INTO [TestSchema].[Course] VALUES('Ecology',10);
INSERT INTO [TestSchema].[Course] VALUES('Latin',364);
INSERT INTO [TestSchema].[Course] VALUES('Modern Literature',643);
INSERT INTO [TestSchema].[Course] VALUES('Economics',278);
INSERT INTO [TestSchema].[Course] VALUES('Basic Math',861);
INSERT INTO [TestSchema].[Course] VALUES('Ancient Civilizations',450);
INSERT INTO [TestSchema].[Course] VALUES('Grammar',153);
INSERT INTO [TestSchema].[Course] VALUES('German',27);
INSERT INTO [TestSchema].[Course] VALUES('LOGIC',730);

